/**
 * Mock / fallback data used when the real API key is absent or for unit tests.
 * This keeps the app fully functional out of the box.
 */

import {
  NewsArticle,
  StockQuote,
  StockRecommendation,
  InvestmentGoal,
} from '../types';

// ─── Mock News ────────────────────────────────────────────────────────────────

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: '1',
    headline: 'Fed signals potential rate cuts as inflation eases toward target',
    summary:
      'Federal Reserve officials indicated they may begin cutting interest rates in the coming months as inflation data shows continued progress toward the 2% target, boosting equity markets.',
    source: 'Reuters',
    url: 'https://example.com/fed-rate-cuts',
    image: 'https://picsum.photos/seed/news1/400/200',
    datetime: Math.floor(Date.now() / 1000) - 3600,
    category: 'general',
    related: 'SPY,QQQ',
    sentiment: 'positive',
  },
  {
    id: '2',
    headline: 'Apple surpasses $3 trillion market cap milestone again',
    summary:
      'Apple Inc. crossed the $3 trillion market capitalisation mark for the second time, driven by strong iPhone sales and growing services revenue.',
    source: 'Bloomberg',
    url: 'https://example.com/apple-3t',
    image: 'https://picsum.photos/seed/news2/400/200',
    datetime: Math.floor(Date.now() / 1000) - 7200,
    category: 'general',
    related: 'AAPL',
    sentiment: 'positive',
  },
  {
    id: '3',
    headline: 'NVIDIA posts record quarterly revenue on AI chip demand',
    summary:
      'NVIDIA reported record revenue of $26 billion for the quarter, far exceeding analyst estimates, as demand for its data centre GPUs powering AI workloads continues to surge.',
    source: 'CNBC',
    url: 'https://example.com/nvidia-revenue',
    image: 'https://picsum.photos/seed/news3/400/200',
    datetime: Math.floor(Date.now() / 1000) - 10800,
    category: 'earnings',
    related: 'NVDA',
    sentiment: 'positive',
  },
  {
    id: '4',
    headline: 'Middle East tensions weigh on oil prices and airline stocks',
    summary:
      'Escalating geopolitical tensions in the Middle East pushed crude oil prices higher while airline stocks fell on concerns over rising fuel costs and potential disruptions to air travel.',
    source: 'Financial Times',
    url: 'https://example.com/mideast-oil',
    image: 'https://picsum.photos/seed/news4/400/200',
    datetime: Math.floor(Date.now() / 1000) - 18000,
    category: 'geopolitical',
    related: 'XOM,DAL,UAL',
    sentiment: 'negative',
  },
  {
    id: '5',
    headline: 'Bitcoin breaks $70,000 as ETF inflows accelerate',
    summary:
      'Bitcoin surged past $70,000 driven by sustained inflows into spot Bitcoin ETFs and renewed retail interest, with analysts pointing to the upcoming halving as a key catalyst.',
    source: 'CoinDesk',
    url: 'https://example.com/btc-70k',
    image: 'https://picsum.photos/seed/news5/400/200',
    datetime: Math.floor(Date.now() / 1000) - 21600,
    category: 'crypto',
    related: 'MSTR,COINBASE',
    sentiment: 'positive',
  },
  {
    id: '6',
    headline: 'Dollar strengthens as strong jobs data dims rate-cut hopes',
    summary:
      'The US dollar rallied to a three-month high after non-farm payrolls data showed robust job creation, reducing expectations for near-term Federal Reserve rate cuts.',
    source: 'MarketWatch',
    url: 'https://example.com/dollar-jobs',
    image: 'https://picsum.photos/seed/news6/400/200',
    datetime: Math.floor(Date.now() / 1000) - 28800,
    category: 'forex',
    related: 'DXY',
    sentiment: 'neutral',
  },
  {
    id: '7',
    headline: 'Microsoft announces $10 billion AI infrastructure expansion',
    summary:
      'Microsoft revealed plans to invest $10 billion in AI infrastructure over the next two years, including new data centres in 10 countries to support its rapidly growing Azure AI services.',
    source: 'The Verge',
    url: 'https://example.com/msft-ai',
    image: 'https://picsum.photos/seed/news7/400/200',
    datetime: Math.floor(Date.now() / 1000) - 36000,
    category: 'general',
    related: 'MSFT',
    sentiment: 'positive',
  },
  {
    id: '8',
    headline: 'Tesla cuts vehicle prices again amid competitive pressure',
    summary:
      'Tesla reduced prices on its Model 3 and Model Y vehicles in key markets for the third time this year as competition from Chinese EV makers intensifies and inventory levels rise.',
    source: 'Electrek',
    url: 'https://example.com/tesla-cuts',
    image: 'https://picsum.photos/seed/news8/400/200',
    datetime: Math.floor(Date.now() / 1000) - 43200,
    category: 'general',
    related: 'TSLA',
    sentiment: 'negative',
  },
];

// ─── Mock Stocks ──────────────────────────────────────────────────────────────

export const MOCK_STOCKS: StockQuote[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    currentPrice: 189.3,
    change: 2.45,
    changePercent: 1.31,
    high: 190.5,
    low: 186.8,
    open: 187.2,
    previousClose: 186.85,
    marketCap: 2950000,
    volume: 58430000,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    currentPrice: 875.4,
    change: 23.6,
    changePercent: 2.77,
    high: 882.0,
    low: 851.3,
    open: 856.0,
    previousClose: 851.8,
    marketCap: 2160000,
    volume: 41200000,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    currentPrice: 415.2,
    change: -1.8,
    changePercent: -0.43,
    high: 418.9,
    low: 413.1,
    open: 417.0,
    previousClose: 417.0,
    marketCap: 3080000,
    volume: 22100000,
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    currentPrice: 173.8,
    change: 3.2,
    changePercent: 1.88,
    high: 175.4,
    low: 170.9,
    open: 171.2,
    previousClose: 170.6,
    marketCap: 2180000,
    volume: 25600000,
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    currentPrice: 198.5,
    change: -2.3,
    changePercent: -1.15,
    high: 202.1,
    low: 197.4,
    open: 201.5,
    previousClose: 200.8,
    marketCap: 2050000,
    volume: 34900000,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    currentPrice: 177.6,
    change: -5.4,
    changePercent: -2.95,
    high: 184.2,
    low: 176.9,
    open: 183.0,
    previousClose: 183.0,
    marketCap: 565000,
    volume: 98600000,
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    currentPrice: 502.3,
    change: 8.7,
    changePercent: 1.76,
    high: 505.8,
    low: 493.2,
    open: 494.0,
    previousClose: 493.6,
    marketCap: 1290000,
    volume: 17800000,
  },
  {
    symbol: 'BRK.B',
    name: 'Berkshire Hathaway Inc.',
    currentPrice: 394.1,
    change: 1.2,
    changePercent: 0.31,
    high: 395.6,
    low: 392.0,
    open: 393.0,
    previousClose: 392.9,
    marketCap: 859000,
    volume: 3400000,
  },
];

// ─── Mock Recommendations ─────────────────────────────────────────────────────

export const MOCK_RECOMMENDATIONS: StockRecommendation[] = [
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    rating: 'strongBuy',
    targetPrice: 1050,
    currentPrice: 875.4,
    analyst: 'Consensus (42 analysts)',
    reason: '90% of analysts rate bullish. Strong AI demand tailwinds and dominant data-centre GPU position support continued revenue growth.',
    updatedAt: Math.floor(Date.now() / 1000) - 86400,
    strongBuy: 32,
    buy: 6,
    hold: 3,
    sell: 1,
    strongSell: 0,
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    rating: 'buy',
    targetPrice: 220,
    currentPrice: 189.3,
    analyst: 'Consensus (38 analysts)',
    reason: '71% of analysts are bullish. Services growth and emerging AI integration expected to re-accelerate revenue in the next fiscal year.',
    updatedAt: Math.floor(Date.now() / 1000) - 172800,
    strongBuy: 18,
    buy: 9,
    hold: 9,
    sell: 2,
    strongSell: 0,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    rating: 'hold',
    targetPrice: 195,
    currentPrice: 177.6,
    analyst: 'Consensus (40 analysts)',
    reason: '38% bullish, 35% hold. Price war pressure and margin compression offset by FSD and energy storage growth potential.',
    updatedAt: Math.floor(Date.now() / 1000) - 259200,
    strongBuy: 8,
    buy: 7,
    hold: 14,
    sell: 8,
    strongSell: 3,
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    rating: 'strongBuy',
    targetPrice: 600,
    currentPrice: 502.3,
    analyst: 'Consensus (44 analysts)',
    reason: '88% bullish. Year of Efficiency results continue to impress; AI-driven ad targeting boosting ARPU across all platforms.',
    updatedAt: Math.floor(Date.now() / 1000) - 86400,
    strongBuy: 29,
    buy: 10,
    hold: 4,
    sell: 1,
    strongSell: 0,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    rating: 'buy',
    targetPrice: 480,
    currentPrice: 415.2,
    analyst: 'Consensus (50 analysts)',
    reason: '84% bullish. Azure AI services growth accelerating; Copilot integration driving enterprise software upgrades.',
    updatedAt: Math.floor(Date.now() / 1000) - 172800,
    strongBuy: 28,
    buy: 14,
    hold: 7,
    sell: 1,
    strongSell: 0,
  },
];

// ─── Mock Goals ───────────────────────────────────────────────────────────────

export const MOCK_GOALS: InvestmentGoal[] = [
  {
    id: 'goal1',
    title: 'Retirement Fund',
    type: 'growth',
    targetAmount: 500000,
    currentAmount: 87500,
    deadline: Math.floor(Date.now() / 1000) + 86400 * 365 * 20,
    riskLevel: 'medium',
    sectors: ['Technology', 'Healthcare', 'Finance'],
    notes: 'Long-term diversified growth portfolio',
    createdAt: Math.floor(Date.now() / 1000) - 86400 * 90,
  },
  {
    id: 'goal2',
    title: 'Dividend Income',
    type: 'income',
    targetAmount: 24000,
    currentAmount: 8400,
    deadline: Math.floor(Date.now() / 1000) + 86400 * 365 * 3,
    riskLevel: 'low',
    sectors: ['Utilities', 'REITs', 'Consumer Staples'],
    notes: 'Annual dividend income target of $2,000/month',
    createdAt: Math.floor(Date.now() / 1000) - 86400 * 45,
  },
];
